"""Type stubs for the Rust extension module."""

from collections.abc import Callable
from typing import Any

def __build_probe() -> str: ...
def roundtrip_ir(json: str) -> str: ...
def render_to_mp4(
    ir: Any,
    out: str,
    fps: int | None = ...,
    crf: int | None = ...,
    progress: Callable[[int, int], None] | None = ...,
) -> None: ...
def eval_at(ir: Any, t: float) -> Any: ...
def tex_validate(src: str) -> None: ...
def render_frame(ir: Any, out: str, t: float) -> None: ...
def install_trace_json(path: str) -> bool: ...
