"""Type stubs for the Rust extension module."""

from typing import Any

def __build_probe() -> str: ...
def roundtrip_ir(json: str) -> str: ...
def render_to_mp4(ir: Any, out: str, fps: int | None = ...) -> None: ...
def eval_at(ir: Any, t: float) -> Any: ...
